# Generated by Django 5.2.17 on 2026-09-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('course', models.CharField(blank=True, max_length=80)),
                ('kind', models.CharField(choices=[('assignment', 'Assignment'), ('exam', 'Exam')], default='assignment', max_length=10)),
                ('due_at', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['completed', 'due_at', 'id'],
            },
        ),
    ]
