# Generated by Django 5.2.17 on 2026-09-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_hours',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 hour'), (24, '1 day'), (48, '2 days')], default=48),
        ),
    ]
