# Generated by Django 5.2.17 on 2026-09-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_reminder_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recurrence_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_days',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Never'), (1, 'Daily'), (7, 'Weekly')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat_timezone',
            field=models.CharField(default='UTC', max_length=64),
        ),
    ]
