# Generated by Django 5.2.17 on 2026-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_task_recurrence_generated_task_repeat_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuietHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('start', models.TimeField(default='22:00')),
                ('end', models.TimeField(default='08:00')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
        ),
    ]
